POST https://localhost/insert
Content-Type: application/json

{
    "things": [
        {
            "type": "date",
            "id": "1984-01-01"
        }
    ]
}

###

POST https://localhost/insert
Content-Type: application/json

{
    "things": [
        {
            "type": "date",
            "id": "1984-01-50"
        }
    ]
}
